name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: examples
        path: examples/*.pdf
        
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        file: examples/*.pdf
