name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: examples
        path: examples/*.pdf
        
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: examples
        path: examples/*.pdf
        
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
